steps:
  - id: docker-compose
    name: 'docker/compose:1.19.0'
    args: ['-f', 'docker-compose.yml', '-f', 'docker-compose.ci.yml', 'up', '-d']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--tag=eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}-${SHORT_SHA}', '.' ]
    waitFor: [docker-compose]

images: [ 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}-${SHORT_SHA}' ]
