steps:
  - id: docker-compose
    name: 'docker/compose:1.19.0'
    args: ['-f', '.cloudbuild/docker-compose.yaml', 'up', '-d']
  - id: test
    name: golang
    args: ['sh', '-c', '.cloudbuild/testrunner.sh']
    waitFor: [docker-compose]
  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--tag=eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${TAG_NAME}', '.' ]
    waitFor: [test]

images: [ 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}-${SHORT_SHA}' ]
