substitutions:
  _BRANCH_NAME: ${BRANCH_NAME//\//-}

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--tag=${_ARTIFACT_REGISTRY_DOMAIN}/${_TARGET_PROJECT_ID}/${_NIMBUS_DOCKER_ARTIFACTS}/${REPO_NAME}:${_BRANCH_NAME}-${SHORT_SHA}', '.' ]

images: ['${_ARTIFACT_REGISTRY_DOMAIN}/${_TARGET_PROJECT_ID}/${_NIMBUS_DOCKER_ARTIFACTS}/${REPO_NAME}:${_BRANCH_NAME}-${SHORT_SHA}']
