steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--tag=eu.gcr.io/${_TARGET_PROJECT_ID}/${REPO_NAME}:${TAG_NAME}', '.' ]

images: ['eu.gcr.io/${_TARGET_PROJECT_ID}/${REPO_NAME}:${TAG_NAME}']
