steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--tag=${_ARTIFACT_REGISTRY_DOMAIN}/${_TARGET_PROJECT_ID}/${_NIMBUS_DOCKER_ARTIFACTS}/${REPO_NAME}:${TAG_NAME}', '.' ]

images: ['${_ARTIFACT_REGISTRY_DOMAIN}/${_TARGET_PROJECT_ID}/${_NIMBUS_DOCKER_ARTIFACTS}/${REPO_NAME}:${TAG_NAME}']
